mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('todolists/', include('todolists.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

todolists/urls.py
from django.urls import path

from . import views

app_name = 'todolists'
urlpatterns = [
    path('', views.base, name='base'),
    path(r'^<int:todolist_id>/$', views.details, name='details'),
    path(r'^complete_task/$', views.complete_task, name='complete_task'),
    path(r'^<str:chosen_date>/completed_tasks/$', views.completed_this_day, name='completed_tasks'),
    path(r'^test.html', views.test, name="test"),
    path(r'add_task/', views.add_task, name='add_task'),
]

todolists/models.py
"""Models used by the todolists app"""
#import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class TodoList(models.Model):
    """Defines the attributes of a TODO list"""
    list_title = models.CharField(max_length=50)
    created_date = models.DateTimeField('date published')
    def __str__(self):
        return self.list_title
    """def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)"""

class Task(models.Model):
    """Defines the attributes of a task from a todo list"""
    assigned_to = models.ForeignKey(User,
                                    models.SET_NULL,
                                    blank=True,
                                    null=True,
                                    default='',
                                    related_name="assigned_task",
                                    related_query_name='assigned_tasks',
                                    verbose_name='Assigned to')
    created_by  = models.ForeignKey(User,
                                    blank=True,
                                    null=True,
                                    on_delete=models.CASCADE,
                                    related_name='created_task',
                                    related_query_name='created_tasks',
                                    verbose_name='Created by')
    todolist = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    task_text = models.CharField(max_length=200)
    is_completed = models.BooleanField(default=False)
    due_date = models.DateField('Due Date', blank=True, null=True)
    completed_date = models.DateField('Completed Date', blank=True, null= True)
    created_date = created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.task_text

todolists/views.py
from django.shortcuts   import render, get_object_or_404
from django.utils       import timezone
from django.http        import HttpResponse
from django.template    import loader

from .models import TodoList, Task


def base(request):
    all_lists = TodoList.objects.order_by('-created_date')
    context = {
        'all_lists' : all_lists,
    }
    return render(request, 'todolists/base.html', context)

def details(request, todolist_id):
    # todolist = TodoList.objects.get(pk=todolist_id)
    todolist = get_object_or_404(TodoList, pk=todolist_id)
    return render(request, 'todolists/details.html', {'todolist':todolist})

def complete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.is_completed = False if task.is_completed else True
    task.save()
    print("task saved: "+task.task_text)
    print("task is_completed: "+ str(task.is_completed))
    return base(request)

def completed_this_day(request, chosen_date):
    """Returns the tasks related to the logged user that were completed in the chosen date"""
    if request.user.is_authenticated():
        user_tasks = request.user.created_tasks_set.filter(complete_task=True, completed_date=chosen_date)
        user_tasks += request.user.assigned_tasks_set.filter(complete_task=True, completed_date=chosen_date)
    else:
        # Show some message when the user is not authenticated
        user_tasks = ''
    return render(request, 'todolists/completed_tasks.html', {'user_tasks':user_tasks})

def test(request):
    return render(request, 'todolists/test.html')

def add_task(request):
    """Adds a new task to the current todo list"""
    print("enter add_task")
    todo_list_id = request.POST['todolist_id']
    #task_text = request.POST['task_text']
    print("todolist id:",todo_list_id)
    #todolist = get_object_or_404(TodoList, pk=todolist_id)

todolists/templates/todolists/base.html
{% load static %} {% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>

<head>
    <link href='https://fonts.googleapis.com/css?family=Advent Pro' rel='stylesheet' type="text/css">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>To do, today</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Acme' rel='stylesheet' type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/todolists.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>

<body>
    <!--<div id="App1"></div>
        {% render_bundle 'vendors' %}
        {% render_bundle 'App1' %}-->
        
    <header id="top" class="header-main">
        <div class="header-main--inside d-flex flex-column">
            <div class="header-main--social">
                Sin in/ Sign up
            </div>


            <div class="header-main-content container align-self-center text-center">
                <h1 class="header-main-content__title">
                    TO DO
                    <br/> TODAY
                </h1>
                <hr class="header-main--lines align-self-start" />
                <p class="header-main-content__text">
                    don't wait for tomorrow
                    <br/> to become productive
                </p>
            </div>

        </div>

    </header>

    <div class="todolists-container d-flex flex-row">
        {% if all_lists %} {% for todolist in all_lists %}
        <div class="card">
            <!--<li><a href="{% url 'todolists:details' todolist.id %}">{{ todolist.list_title }}</a></li>-->
            {% include "todolists/details.html" with todolist=todolist %}
        </div>
        {% endfor %}
        <div class="btn-new_list-container d-flex flex-column">
            <div class="align-self-center">
                <button class="btn-new_list" name="btn-new_list"> New TODO List </button>
            </div>
        </div>
        {% else %}
        <p>Start today!</p>
        <p>Create your first TODO list.</p>
        {% endif %}
    </div>

    <!-- SCRIPTS -->
    <script src="{% static 'scripts/todolists.js' %}"></script>
    <script src="bundle.js"></script>

</body>

</html>

todolists/templates/todolists/details.html
<!-- details of a TODO list -->
<script>
    let todolist_id = {{ todolist.id }};
    console.log("Initializing todolistId: "+ todolistId);
</script>


<div class="card-title">
    <h1> {{ todolist.list_title}} </h1>
</div>

<div class="card-container">
    <form>
    {% csrf_token%}
        {% for task in todolist.task_set.all %}
            <div class="list_item" id="task-{{ task.id }}" data-taskid="{{ task.id }}" data-listid="{{ todolist.id }}" onclick="check_task(this.id)">
                <span class="dot" name="task-{{ task.id }}"></span>
                <!--<input type="checkbox" name="task" id="task{{ forloop.counter }}" value="{{ task.id }}" />
                <label for="task{{ forloop.counter }}">{{ task.task_text }}</label>-->
                <span class="task" id="{{ task.id }}" name="task-{{ task.id }}">{{ task.task_text }}</span>
            </div>
            <br />

        {% endfor %}

        <div class="list_item">
            <span class="dot" ></span>
            <input type="text" placeholder="new task" class="new_task"/>
        </div>
    </form>
</div>

todolists/templates/todolists/test.html
{% extends "todolists/details.html" %}
{% load render_bundle from webpack_loader %}

{% block main %}
<div id="App1"></div>
{% render_bundle 'vendors' %}
{% render_bundle 'App1' %}
{% endblock %}